site_name: 强智教务系统API文档
theme:
  name: 'material'
  language: 'zh'
  features:
    - tabs
    
repo_name: TLingC/QZAPI
repo_url: https://github.com/TLingC/QZAPI
edit_uri: 'edit/master/docs'

google_analytics: ['UA-139537764-1', 'qzapi.github.tlingc.com']

nav:    
  - '首页':
    - '关于文档': index.md
    - '支持学校': support.md
  - 'API':
    - '开发前必读': api/index.md
    - '登录': api/authUser.md
    - '时间信息': api/getCurrentTime.md
    - '课程信息': api/getKbcxAzc.md
    - '成绩信息': api/getCjcx.md
    - '考试信息': api/getKscx.md
    - '学籍预警信息': api/getEarlyWarnInfo.md
    - '教学楼信息': api/getJxlcx.md
    - '空教室信息': api/getKxJscx.md
    - '用户信息': api/getStudentIdInfo.md
    - '账号信息': api/getUserInfo.md
    - '学年学期信息': api/getXnxq.md
    - '校区信息': api/getXqcx.md
  - '相关项目':
    - 'PHP': related/php.md
    - 'Python': related/python.md
    - '微信小程序': related/wechat_miniprogram.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true